### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by shelld3v**
I don't want to wait 3 minutes for a request!!!

Out of scope: I think we should remove `500` from the retry status codes! What do you think?

### CODE REVIEW

**Comment by shelld3v** [comment]
Another out of scope: I think that Amass should also crawl URLs from `<script>` src:

```golang
			r.HTMLDoc.Find("a").Each(func(i int, s *goquery.Selection) {
				if href, ok := s.Attr("href"); ok {
					if count < 5 {
						g.Get(r.JoinURL(href), g.Opt.ParseFunc)
						count++
					}
				}
			}
+						
+			r.HTMLDoc.Find("script").Each(func(i int, s *goquery.Selection) {
+				if src, ok := s.Attr("src"); ok {
+					if count < 10 {
+						g.Get(r.JoinURL(src), g.Opt.ParseFunc)
+						count++
+					}
+				}
+			}
```

**Comment by shelld3v** [comment]
And WTF `count < 5`?

**Comment by shelld3v** [comment]
I did it btw!! Also increased the timeout a little bit after saw you didn't merge my PR, maybe you are feeling uncertain about my PR!?!

**Review by caffix — APPROVED** [review]
Great!

**Pull request merged**
