### PR TITLE
Add "hashcat-style" Wordlist Masks

### PR DESCRIPTION
**Pull request by fork-while-fork**
This pull request adds "hashcat-style" wordlist masks to the alterations and brute force engines. Users will now be able to include words such as:

`www-?l?l?l `

in their wordlist which would discover names such as:

```
www-dev
www-uat
```

The character classes that are supported include:

```
?l = a-z
?u = a-z
?d = 0-9
?s = -
?a = ?l?d?s
```

### CODE REVIEW

**Comment by NanoDano** [comment]
My initial thought was "is there a flag to disable or enable this?" but realized a `?` is never valid in a domain name. I could only think of a couple contrived examples of where someone might want to turn this feature off though. Something to consider, or leave for the person who actually needs it.

Also, it looks like there is a hard-coded mask limit of 3? Am I misreading that? Any particular reason for that? Might consider making that limit configurable.

**Comment by caffix** [comment]
If we allow the mask to get too large, it will create too many name alteration and brute forcing attempts. We could allow users to create this situation...

**Comment by fork-while-fork** [comment]
Yeah the hardcoded limit of 3 is because the worst case for a 3 character mask is about 50k words, while the worst case for 4 is almost 2 million. I considered implementing a feature to give an exact count so the masks could be a little more flexible, but the simpler implementation won out in the end. I think we can revisit if users ask for more flexibility.

Users can avoid using masks by not including them in their lists. The default lists don't have any masks, but if we do add masks to them in the future, it won't be without consideration of the implications.

**Comment by pielgrzym** [comment]
It would be really good if amass alerted about this 3 letter limit exceeded instead of defaulting to wordlist bruteforce. I wasted almost an hour going through docs and codebase to discover this middle finger here ;)

**Pull request merged**
