### PR TITLE
Prune Services Redux

### PR DESCRIPTION
**Pull request by alrs**
This prunes an unused function and an unused variable from the `services` package, replacing https://github.com/OWASP/Amass/pull/365.

### CODE REVIEW

**Comment by caffix** [comment]
Thank you. The base branch needs to be set to `develop`

**Comment by alrs** [comment]
Changed to `develop`, thanks for the reminder.

**Comment by alextudu** [comment]
Redux is a great tool that solves one of the main problems of UI frameworks: **state management**. It is advisable to keep the Redux service at the moment as the development for web interface with API calling is currently in progress. The solutions I have researched also justifies that React(web development solution for Amass) is quite compatible and favorable with Redux.

**Comment by alrs** [comment]
@alextudu I'm using the dictionary definition of the word "redux," no reference is being made here to the Javascript project of the same name. This is a "do-over," or "redux" of a previous PR named "Prune Services."

**Pull request merged**
