### PR TITLE
Fix the example for using Amass as a package

### PR DESCRIPTION
**Pull request by faheel**
The code I've updated is the same as that in [`examples/minimal.go`](https://github.com/OWASP/Amass/blob/master/examples/minimal.go)

### CODE REVIEW

**Comment by faheel** [comment]
I had to set `cfg.Dir` to `"/tmp"` in the code I've added. Not doing so would give me a "Failed to create the graph" error. Should I add this as a note after the example?

> If you get an error saying "Failed to create the graph", try changing the output directory in config:
> ```go
> cfg := config.NewConfig()
> cfg.Dir = "/tmp"
> 
> sys, err := services.NewLocalSystem(cfg)
> ```

**Comment by caffix** [comment]
@faheel You can go ahead and add that to your contribution.

What operating system were you running the program on that caused the graph to not be created? Not setting the value should cause the default location to be used

**Comment by faheel** [comment]
@caffix I was running it on Amazon Linux (AWS Lambda).

**Comment by vrechson** [comment]
I couldn't make it work, i had to change to 

```
	os.Remove("/tmp/amass/indexes.bolt")

	cfg := config.NewConfig()
	cfg.Dir = "/tmp/amass/"

	sys, err := services.NewLocalSystem(cfg)
```

**Pull request merged**
