### PR TITLE
Add FUNDING.yml

### PR DESCRIPTION
**Pull request by kingthorin**
With custom entry pointing to the foundation donation functionality and github sponsors ORG ref.

(Sets up the "Sponsor ♥" button for this repo.)

### CODE REVIEW

**Comment by kingthorin** [comment]
The lint failure is totally unrelated. No go code is impacted by this PR.

**Comment by kingthorin** [comment]
Ping @caffix

**Review by caffix — APPROVED** [review]
Thanks!

**Comment by kingthorin** [comment]
No problem, happy to help. Thanks for the merge.

**Comment by kingthorin** [comment]
Hmm it doesn't seem to have taken effect because it was merged into develop vs the default which seems to be master.

**Comment by caffix** [comment]
It will come out with the next release

**Comment by kingthorin** [comment]
Okay, no problem here. Just wanted to make sure it was clear if anyone else was trying to sort it out :wink:

**Pull request merged**
