### PR TITLE
Updated Config.ini with api source links and type

### PR DESCRIPTION
**Pull request by CowlingBanana**

### CODE REVIEW

**Comment by CowlingBanana** [comment]
@caffix Please look into this!

**Review by caffix — CHANGES_REQUESTED** [review]
The `[data_sources.link]=` are not necessary in the comments. Just the information after the equals sign will be enough

**Review by CowlingBanana — COMMENTED** [review]
Done @caffix, please check!

**Comment by caffix** [comment]
@CowlingBanana if you have more information about registering for the data sources, would you like to make a markdown file for the documentation?

**Review by caffix — APPROVED** [review]
Thank you for your contribution!

**Comment by CowlingBanana** [comment]
> @CowlingBanana if you have more information about registering for the data sources, would you like to make a markdown file for the documentation?

@caffix  Yes, would love to, what information would we be looking for? Steps on registering and acquiring the api key's with screenshots of it.

**Comment by CowlingBanana** [comment]
@caffix ?

**Comment by caffix** [comment]
Let's take this discussion to the Discord server. Please DM me when you get there

**Pull request merged**
