### PR TITLE
Added a reference to the "mentions" section in README.md

### PR DESCRIPTION
**Pull request by 0xbharath**
I have added a new reference (medium blog post) to the "mentions" section in README.md

### CODE REVIEW

**Comment by caffix** [comment]
Thank you for the PR. Please submit this contribution to the develop branch

**Comment by 0xbharath** [comment]
Thanks for the reply. I will raise a PR against develop branch.

**Comment by 0xbharath** [comment]
Thanks for merging. I have gone through `CONTRIBUTING.md` document now. I'll follow the general rules for contribution from now on.

**Comment by caffix** [comment]
Thanks again for the contribution!

**Pull request merged**
