### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by shelld3v**

### CODE REVIEW

**Comment by caffix** [comment]
Unnecessary

**Comment by shelld3v** [comment]
> Unnecessary

I just want to clean the log file:

```
...
19:15:24.725085 IPinfo: asn callback: <string>:77: bad argument #1 to sub (string expected, got nil)
stack traceback:
        [G]: in function 'sub'
        <string>:77: in function 'getasn'
        <string>:43: in main chunk
        [G]: ?
19:15:24.725150 VirusTotal: vertical callback: <string>:45: bad argument #1 to pairs (table expected, got nil)
stack traceback:
        [G]: in function 'pairs'
        <string>:45: in main chunk
        [G]: ?
...
```

**Comment by caffix** [comment]
What about a similar check for the use of `d.data` in the else block?

**Review by caffix — APPROVED** [review]
Thank you for the additional error checking

**Pull request merged**
