### PR TITLE
Data Source Unit Tests

### PR DESCRIPTION
**Pull request by VltraHeaven**

### CODE REVIEW

**Comment by KJ202** [comment]
Hey
Sorry I come a bit late. I was wondering if we could not slightly improve this test.
Currently, censys has 2 code paths depending on the API keys provided:
- The API keys are actually provided, the appropriate API will be used
- The API keys are empty strings, censys.go will try to directly fetch the information using a url

The current implementation of the test would not allow us to explore the second path as the test would not accept empty string as API keys.

We could either:

- Only check whether config.API is different from null and therefore give the option to the tester to provide empty strings as API keys
- Write another test function for the second path

**Comment by caffix** [comment]
@KJ202 I appreciate you noticing this, and would like to see the second path tested as well. Can you take on this task and submit it as a separate PR?

**Comment by KJ202** [comment]
@caffix Sure, I'll handle it.

**Comment by caffix** [comment]
Thank you, and please write the second test function

**Pull request merged**
