### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by jimen0**
This PR introduces a set of commits that aim to simplify the code base a bit. They mostly remove unneeded logical statements and unused code (functions, methods and constants).

I tried to follow contribution guidelines, but let me know if I missed something. I also tried to split the commits in small, independent changes, however let me know if you prefer me to squash them into a single change.

By the way, this PR also enables the existing test under `viz_test.go` by renaming the test (`FooTest` to `TestFoo`) and introducing a test case to the testing table.

As I saw no "how to test your changes" in the contribution guidelines, I tested them by running the test suite with the race detector enabled under Go 1.15 and tip. Both passed all the tests and binary was correctly built.

Best,
Miguel

### CODE REVIEW

**Comment by jimen0** [comment]
Force-push was to sync with `Amass/develop` as I originally picked `Amass/master` instead. Sorry about that (:

**Comment by caffix** [comment]
The changes I'm about to bring to `develop` will throw off this PR, and we have never allowed force pushes. Please branch from the updated develop branch and resubmit the changes. Thank you!

**Comment by jimen0** [comment]
Lol, what a nice experience for your contributors.

> The changes I'm about to bring to develop will throw off this PR

Are you sure the applied changes to `develop` completely threw of this PR? Because I see many of the fixed problems still apply there.

Also, I force pushed against my local branch in order to rebase it against `Amass/develop`, it doesn't matter at all for your project, there's no need to close and reopen this PR.

Regards,

**Comment by jimen0** [comment]
Closing in favor of #472

**Pull request closed without merging**
