### PR TITLE
fixed go install

### PR DESCRIPTION
**Pull request by vaishnavpardhi**
go install was not working giving error matched no packages,,adding GO111MODULE=on before go get fixed the issue.

### CODE REVIEW

**Comment by caffix** [comment]
We used to recommend the same, yet Golang has indicated that the environment variable shouldn't need to be set in recent versions (e.g. 1.16). What version of Golang are you using?

**Comment by vaishnavpardhi** [comment]
I tested on kali linux,go version is go1.15.6 (which is latest in kali by sudo apt install golang) ,,haven't tested on go version 1.16,,let me try :)

**Comment by vaishnavpardhi** [comment]
Yeah i test on go1.16.6,,,actually both way works `GO111MODULE=on go get -v github.com/OWASP/Amass/v3/...` and `go get -v github.com/OWASP/Amass/v3/...` But i suggest GO111MODULE=on for the amass repo, because most of debain based distro installs golang version(by sudo apt install golang) less than 1.16 and to work amass on it GO111MODULE=on is required.

**Comment by caffix** [comment]
The Amass Project indicates on the README.md that it requires Go version 1.16 when building from source. Thank you for your contribution!

**Pull request closed without merging**
