### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by blshkv**
add Pentoo installation instructions

### CODE REVIEW

**Comment by caffix** [comment]
We cannot be putting every package installation process on the README, but we are updating the documentation, and these processes can be included there

**Comment by blshkv** [comment]
That sounds unfair. You are advertising our competitor on the main page.
Please remove it and redirect Linux users to the relevant  section of the documentation.

**Comment by caffix** [comment]
Soon, we will be moving all the installation instructions to the appropriate documentation. We are not attempting to show favoritism toward any operating system

**Comment by caffix** [comment]
I am working on the installation guild right now

**Pull request closed without merging**
